import os
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = 'https://eu.api.smith.langchain.com'
os.environ['LANGCHAIN_PROJECT'] = 'myLLM'
from dotenv import load_dotenv
load_dotenv()

import bs4
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from code_learning import utils
from operator import itemgetter

splits = utils.get_example_docsplits() #loads a set of agentic AI papers from the web
retriever = utils.get_retriever(splits=splits)

# Multi Query: Different Perspectives
template = """Read the following user query Original question: {question}"""
prompt_perspectives = ChatPromptTemplate.from_template(template)
local_qwen_path = '/Users/bill/Documents/qwen_3.5_8B'

llm_qt = utils.get_qwen_pipeline(local_qwen_path, max_new_tokens=200)
generate_queries = (
    prompt_perspectives
    | llm_qt
    | StrOutputParser()
    | (lambda x: x.split("\n"))
)

# Retrieve using the multiple queries generated above. Learning: found that it was actually pretty hard to rely on the LLM
# nicely-formatted queries. For a start, the first model I used wasn't an instruct finetuned model. This resulted in infinite-loop
# outputs.
question = "What is the most profound use of agentic AI and RAG?"
retrieval_chain = generate_queries | retriever.map() | utils.get_top_unique_documents # retriever.map() is doing something clever here - it is retrieving for each of the elements of the listed generated by 'generated_queries'

# RAG
template = """Answer the following question based on this context:
{context}
Question: {question}
"""

prompt = ChatPromptTemplate.from_template(template)

llm_generation = utils.get_qwen_pipeline(local_qwen_path, max_new_tokens=1000)

final_rag_chain = (
    {"context": retrieval_chain,
     "question": itemgetter("question")}
    | prompt
    | llm_generation
    | StrOutputParser()
)

response = final_rag_chain.invoke({"question":question})
print(response)