import os
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = 'https://eu.api.smith.langchain.com'
os.environ['LANGCHAIN_PROJECT'] = 'myLLM'
from dotenv import load_dotenv
load_dotenv()

import bs4
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import utils

splits = utils.get_example_docsplits() #loads a set of agentic AI papers from the web
retriever = utils.get_retriever(splits=splits)

# Multi Query: Different Perspectives
template = """We have 5 different sources of knowledge: Scientific articles in oncology [SCI_ONC], Case-study articles from radiology [CLI_RAD], Medical textbooks in radiology and oncology [BOOK_MED],
 Local patient management strategies for those suspected and diagnosed with cancer in our hospital centre [PAT_GUI], and a description of insurance policies [INS_POL]. Please determine which of the following knowledge sources the user's
 query will likely need information from, using their variable names. See examples below.
 ------------------------
 Example Query 1: My doctor told me they saw a bump on my CT scan, what are the likely next steps?
 Example Answer 1: [PAT_GUI], [BOOK_MED], [INS_POL]
 
 Example Query 2: How well does AI perform renal cell carcinoma subtyping?
 Example Answer 2: [SCI_ONC]
 
 Example Query 3: I am a doctor reviewing a CT scan, what do you make of this endophytic heterogenous 2cm hypoattenuating mass in the left kidney?
 Example Answer 3: [CLI_RAD], [BOOK_MED]
  ------------------------
 Using the examples above, determine which of knowledge ([SCI_ONC], [CLI_RAD], [BOOK_MED], [PAT_GUI], [INS_POL]) sources would likely help to answer the User Query.
 User Query: {question}"""
prompt_routing = ChatPromptTemplate.from_template(template)
local_qwen_path = '/Users/bill/Documents/qwen_3.5_8B'

llm_qt = utils.get_qwen_pipeline(local_qwen_path, max_new_tokens=200)
generate_route = (
    prompt_routing
    | llm_qt
    | StrOutputParser()
    | (lambda x: x.split("\n"))
)

# Retrieve using the multiple queries generated above. Learning: found that it was actually pretty hard to rely on the LLM
# nicely-formatted queries. For a start, the first model I used wasn't an instruct finetuned model. This resulted in infinite-loop
# outputs.
question = "My doctor recommended that I take a immunotherapy for my lung cancer. He said I should read up on the side effects. What are the side effects of immunotherapy in lung cancer?"
retrieval_chain = generate_route | retriever.map() | utils.get_unique_union # retriever.map() is doing something clever here - it is retrieving for each of the elements of the listed generated by 'generated_queries'

route = generate_route.invoke({"question":question})
print(route)


#structured output requires pydantic, which requires python<3.14, so will leave this out of this script